### ISSUE TITLE
The sensor does not move.

### ISSUE THREAD

**Issue by junhyuck-yoo** [pierosavi/pierosavi-imageit-panel#47]
Hi.
I am currently using version 0.1.3 of IamgeIt.
However, if I try to place a seat after creating a sensor on the panel, it does not move. Is there any way to make the sensor move?
![스크린샷_2020-04-09_10-33-58](https://user-images.githubusercontent.com/52561569/78848758-ab1b8780-7a4d-11ea-8497-a911eb353a06.png)

**Comment by podda94** [comment]
Hi, 
I have the same issue, 
I'm using mozilla and the latest version of ImageIt. 
Sometimes the panel crashes and i cannot move the sensor. I tried to restart grafana and the problem seems disappear but after some while it appears again. I thought might be something related to the lock but i tried with different options and nothing.
The dropping feature is amazing but maybe it could be helpful to have a box where to insert the X value as well as the Y using a % of the image size if not possible to use pixels due to the scaling.

Thanks a lot, this plugins is exactly what i was looking for.

**Comment by IllariPosselt** [comment]
I have the same issue :) I tried Edge, Chrome and Firefox on Windows 10..
